version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
#      - 51773 
# new SuperServer Port
      - 1972
      - 52773
      - 53773
    volumes:
# no license required for community image
#      - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./:/irisdev/app
